---
- hosts: all

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update cache
      apt: update_cache=yes cache_valid_time=3600
  become: yes

  handlers:
    - import_tasks: handlers/handlers.yml

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/apache.yml
    - import_tasks: tasks/composer.yml
    - import_tasks: tasks/drupal.yml
